### ISSUE TITLE
Use my role for oh-my-zsh

### ISSUE THREAD

**Issue by LorenzoBettini** [LorenzoBettini/ansible-ubuntu-playbook#24]
```yaml
  # Install my own roles from GitHub
  - name: lorenzobettini.oh_my_zsh
    src: https://github.com/LorenzoBettini/ansible-molecule-oh-my-zsh-example/
```
